function ES=subgsize(a,b,p)
%outputs all points in E and the size of the subgroup generated by each point
E=EllC(a,b,p);
N=length(E)+1
ES=[E(:,1),E(:,2),zeros(N-1,1)];
for ii=1:N-1
    for jj=1:N
        Q=PMulD(E(ii,:),jj,a,b,p);
        if isscalar(Q)
            ES(ii,3)=jj;
           break
        end
    end
end
        